// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.gamecenter.domain.mq.joingame

object JoingameProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChFtcS9qb2luZ2FtZS5wcm90byLxAQoPSm9pbkdhbWVNZXNzYWdlEhgKB3RyYWNlSWQYASABKAlSB3RyYWNlSWQSGgoIc29ja
  2V0SWQYAiABKANSCHNvY2tldElkEg4KAmlwGAMgASgDUgJpcBIeCgpkZXZpY2VUeXBlGAQgASgFUgpkZXZpY2VUeXBlEiAKC2Zpb
  mdlclByaW50GAUgASgJUgtmaW5nZXJQcmludBIaCghtZW1iZXJJZBgGIAEoA1IIbWVtYmVySWQSGgoIZ2FtZVR5cGUYByABKAVSC
  GdhbWVUeXBlEh4KCmJhc2VBbW91bnQYCCABKAVSCmJhc2VBbW91bnRCIQofY29tLmp4anhnby5nYW1lY2VudGVyLmRvbWFpbi5tc
  WIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}