/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.gamecenter.rpc.domain

import com.twitter.finagle.SourcedException
import com.twitter.finagle.{service => ctfs}
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.finagle.thrift.{Protocols, ThriftClientRequest}
import com.twitter.scrooge.{ThriftStruct, ThriftStructCodec}
import com.twitter.util.{Future, Return, Throw, Throwables}
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.{TMemoryBuffer, TMemoryInputTransport}
import scala.collection.{Map, Set}
import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class GameEndpoint$FinagleClient(
    val service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
    val protocolFactory: TProtocolFactory,
    val serviceName: String,
    stats: StatsReceiver,
    responseClassifier: ctfs.ResponseClassifier)
  extends GameEndpoint[Future] {

  def this(
    service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
    protocolFactory: TProtocolFactory = Protocols.binaryFactory(),
    serviceName: String = "GameEndpoint",
    stats: StatsReceiver = NullStatsReceiver
  ) = this(
    service,
    protocolFactory,
    serviceName,
    stats,
    ctfs.ResponseClassifier.Default
  )

  import GameEndpoint._

  protected def encodeRequest(name: String, args: ThriftStruct) = {
    val buf = new TMemoryBuffer(512)
    val oprot = protocolFactory.getProtocol(buf)

    oprot.writeMessageBegin(new TMessage(name, TMessageType.CALL, 0))
    args.write(oprot)
    oprot.writeMessageEnd()

    val bytes = Arrays.copyOfRange(buf.getArray, 0, buf.length)
    new ThriftClientRequest(bytes, false)
  }

  protected def decodeResponse[T <: ThriftStruct](resBytes: Array[Byte], codec: ThriftStructCodec[T]) = {
    val iprot = protocolFactory.getProtocol(new TMemoryInputTransport(resBytes))
    val msg = iprot.readMessageBegin()
    try {
      if (msg.`type` == TMessageType.EXCEPTION) {
        val exception = TApplicationException.read(iprot) match {
          case sourced: SourcedException =>
            if (serviceName != "") sourced.serviceName = serviceName
            sourced
          case e => e
        }
        throw exception
      } else {
        codec.decode(iprot)
      }
    } finally {
      iprot.readMessageEnd()
    }
  }

  protected def missingResult(name: String) = {
    new TApplicationException(
      TApplicationException.MISSING_RESULT,
      name + " failed: unknown result"
    )
  }

  protected def setServiceName(ex: Throwable): Throwable =
    if (this.serviceName == "") ex
    else {
      ex match {
        case se: SourcedException =>
          se.serviceName = this.serviceName
          se
        case _ => ex
      }
    }

  // ----- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_playerOnline {
    val RequestsCounter = scopedStats.scope("playerOnline").counter("requests")
    val SuccessCounter = scopedStats.scope("playerOnline").counter("success")
    val FailuresCounter = scopedStats.scope("playerOnline").counter("failures")
    val FailuresScope = scopedStats.scope("playerOnline").scope("failures")
  }
  
  def playerOnline(traceId: String, request: com.jxjxgo.gamecenter.rpc.domain.OnlineRequest): Future[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] = {
    __stats_playerOnline.RequestsCounter.incr()
    val inputArgs = PlayerOnline.Args(traceId, request)
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] =
      response => {
        val result = decodeResponse(response, PlayerOnline.Result)
        val exception: Throwable =
        null
  
        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("playerOnline"))
      }
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx
    ) {
      val serialized = encodeRequest("playerOnline", inputArgs)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val responseClass = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        responseClass match {
          case ctfs.ResponseClass.Successful(_) =>
            __stats_playerOnline.SuccessCounter.incr()
          case ctfs.ResponseClass.Failed(_) =>
            __stats_playerOnline.FailuresCounter.incr()
            response match {
              case Throw(ex) =>
                setServiceName(ex)
                __stats_playerOnline.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
              case _ =>
            }
        }
      }
    }
  }
  private[this] object __stats_playerOffline {
    val RequestsCounter = scopedStats.scope("playerOffline").counter("requests")
    val SuccessCounter = scopedStats.scope("playerOffline").counter("success")
    val FailuresCounter = scopedStats.scope("playerOffline").counter("failures")
    val FailuresScope = scopedStats.scope("playerOffline").scope("failures")
  }
  
  def playerOffline(traceId: String, socketUuid: Long, memberId: Long): Future[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] = {
    __stats_playerOffline.RequestsCounter.incr()
    val inputArgs = PlayerOffline.Args(traceId, socketUuid, memberId)
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] =
      response => {
        val result = decodeResponse(response, PlayerOffline.Result)
        val exception: Throwable =
        null
  
        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("playerOffline"))
      }
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx
    ) {
      val serialized = encodeRequest("playerOffline", inputArgs)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val responseClass = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        responseClass match {
          case ctfs.ResponseClass.Successful(_) =>
            __stats_playerOffline.SuccessCounter.incr()
          case ctfs.ResponseClass.Failed(_) =>
            __stats_playerOffline.FailuresCounter.incr()
            response match {
              case Throw(ex) =>
                setServiceName(ex)
                __stats_playerOffline.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
              case _ =>
            }
        }
      }
    }
  }
  private[this] object __stats_generateSocketId {
    val RequestsCounter = scopedStats.scope("generateSocketId").counter("requests")
    val SuccessCounter = scopedStats.scope("generateSocketId").counter("success")
    val FailuresCounter = scopedStats.scope("generateSocketId").counter("failures")
    val FailuresScope = scopedStats.scope("generateSocketId").scope("failures")
  }
  
  def generateSocketId(traceId: String): Future[com.jxjxgo.gamecenter.rpc.domain.GenerateSocketIdResponse] = {
    __stats_generateSocketId.RequestsCounter.incr()
    val inputArgs = GenerateSocketId.Args(traceId)
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[com.jxjxgo.gamecenter.rpc.domain.GenerateSocketIdResponse] =
      response => {
        val result = decodeResponse(response, GenerateSocketId.Result)
        val exception: Throwable =
        null
  
        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("generateSocketId"))
      }
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[com.jxjxgo.gamecenter.rpc.domain.GenerateSocketIdResponse](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx
    ) {
      val serialized = encodeRequest("generateSocketId", inputArgs)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val responseClass = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        responseClass match {
          case ctfs.ResponseClass.Successful(_) =>
            __stats_generateSocketId.SuccessCounter.incr()
          case ctfs.ResponseClass.Failed(_) =>
            __stats_generateSocketId.FailuresCounter.incr()
            response match {
              case Throw(ex) =>
                setServiceName(ex)
                __stats_generateSocketId.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
              case _ =>
            }
        }
      }
    }
  }
  private[this] object __stats_checkGameStatus {
    val RequestsCounter = scopedStats.scope("checkGameStatus").counter("requests")
    val SuccessCounter = scopedStats.scope("checkGameStatus").counter("success")
    val FailuresCounter = scopedStats.scope("checkGameStatus").counter("failures")
    val FailuresScope = scopedStats.scope("checkGameStatus").scope("failures")
  }
  
  def checkGameStatus(traceId: String, request: com.jxjxgo.gamecenter.rpc.domain.CheckGameStatusRequest): Future[com.jxjxgo.gamecenter.rpc.domain.CheckGameStatusResponse] = {
    __stats_checkGameStatus.RequestsCounter.incr()
    val inputArgs = CheckGameStatus.Args(traceId, request)
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[com.jxjxgo.gamecenter.rpc.domain.CheckGameStatusResponse] =
      response => {
        val result = decodeResponse(response, CheckGameStatus.Result)
        val exception: Throwable =
        null
  
        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("checkGameStatus"))
      }
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[com.jxjxgo.gamecenter.rpc.domain.CheckGameStatusResponse](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx
    ) {
      val serialized = encodeRequest("checkGameStatus", inputArgs)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val responseClass = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        responseClass match {
          case ctfs.ResponseClass.Successful(_) =>
            __stats_checkGameStatus.SuccessCounter.incr()
          case ctfs.ResponseClass.Failed(_) =>
            __stats_checkGameStatus.FailuresCounter.incr()
            response match {
              case Throw(ex) =>
                setServiceName(ex)
                __stats_checkGameStatus.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
              case _ =>
            }
        }
      }
    }
  }
  private[this] object __stats_joinGame {
    val RequestsCounter = scopedStats.scope("joinGame").counter("requests")
    val SuccessCounter = scopedStats.scope("joinGame").counter("success")
    val FailuresCounter = scopedStats.scope("joinGame").counter("failures")
    val FailuresScope = scopedStats.scope("joinGame").scope("failures")
  }
  
  def joinGame(traceId: String, request: com.jxjxgo.gamecenter.rpc.domain.JoinGameRequest): Future[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] = {
    __stats_joinGame.RequestsCounter.incr()
    val inputArgs = JoinGame.Args(traceId, request)
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] =
      response => {
        val result = decodeResponse(response, JoinGame.Result)
        val exception: Throwable =
        null
  
        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("joinGame"))
      }
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx
    ) {
      val serialized = encodeRequest("joinGame", inputArgs)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val responseClass = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        responseClass match {
          case ctfs.ResponseClass.Successful(_) =>
            __stats_joinGame.SuccessCounter.incr()
          case ctfs.ResponseClass.Failed(_) =>
            __stats_joinGame.FailuresCounter.incr()
            response match {
              case Throw(ex) =>
                setServiceName(ex)
                __stats_joinGame.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
              case _ =>
            }
        }
      }
    }
  }
  private[this] object __stats_takeLandlord {
    val RequestsCounter = scopedStats.scope("takeLandlord").counter("requests")
    val SuccessCounter = scopedStats.scope("takeLandlord").counter("success")
    val FailuresCounter = scopedStats.scope("takeLandlord").counter("failures")
    val FailuresScope = scopedStats.scope("takeLandlord").scope("failures")
  }
  
  def takeLandlord(traceId: String, request: com.jxjxgo.gamecenter.rpc.domain.TakeLandlordRequest): Future[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] = {
    __stats_takeLandlord.RequestsCounter.incr()
    val inputArgs = TakeLandlord.Args(traceId, request)
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] =
      response => {
        val result = decodeResponse(response, TakeLandlord.Result)
        val exception: Throwable =
        null
  
        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("takeLandlord"))
      }
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx
    ) {
      val serialized = encodeRequest("takeLandlord", inputArgs)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val responseClass = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        responseClass match {
          case ctfs.ResponseClass.Successful(_) =>
            __stats_takeLandlord.SuccessCounter.incr()
          case ctfs.ResponseClass.Failed(_) =>
            __stats_takeLandlord.FailuresCounter.incr()
            response match {
              case Throw(ex) =>
                setServiceName(ex)
                __stats_takeLandlord.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
              case _ =>
            }
        }
      }
    }
  }
  private[this] object __stats_playCards {
    val RequestsCounter = scopedStats.scope("playCards").counter("requests")
    val SuccessCounter = scopedStats.scope("playCards").counter("success")
    val FailuresCounter = scopedStats.scope("playCards").counter("failures")
    val FailuresScope = scopedStats.scope("playCards").scope("failures")
  }
  
  def playCards(traceId: String, request: com.jxjxgo.gamecenter.rpc.domain.PlayCardsRequest): Future[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] = {
    __stats_playCards.RequestsCounter.incr()
    val inputArgs = PlayCards.Args(traceId, request)
    val replyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse] =
      response => {
        val result = decodeResponse(response, PlayCards.Result)
        val exception: Throwable =
        null
  
        if (result.success.isDefined)
          _root_.com.twitter.util.Return(result.success.get)
        else if (exception != null)
          _root_.com.twitter.util.Throw(exception)
        else
          _root_.com.twitter.util.Throw(missingResult("playCards"))
      }
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.DeserializeCtx[com.jxjxgo.gamecenter.rpc.domain.GameBaseResponse](inputArgs, replyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.DeserializeCtx.Key,
      serdeCtx
    ) {
      val serialized = encodeRequest("playCards", inputArgs)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val responseClass = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        responseClass match {
          case ctfs.ResponseClass.Successful(_) =>
            __stats_playCards.SuccessCounter.incr()
          case ctfs.ResponseClass.Failed(_) =>
            __stats_playCards.FailuresCounter.incr()
            response match {
              case Throw(ex) =>
                setServiceName(ex)
                __stats_playCards.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
              case _ =>
            }
        }
      }
    }
  }
}
