/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.gamecenter.rpc.domain

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object PlayCardsRequest extends ThriftStructCodec3[PlayCardsRequest] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("PlayCardsRequest")
  val MemberIdField = new TField("memberId", TType.I64, 1)
  val MemberIdFieldManifest = implicitly[Manifest[Long]]
  val CardsField = new TField("cards", TType.STRING, 2)
  val CardsFieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      MemberIdField,
      false,
      false,
      MemberIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      CardsField,
      false,
      false,
      CardsFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: PlayCardsRequest): Unit = {
  }

  def withoutPassthroughFields(original: PlayCardsRequest): PlayCardsRequest =
    new Immutable(
      memberId =
        {
          val field = original.memberId
          field
        },
      cards =
        {
          val field = original.cards
          field
        }
    )

  override def encode(_item: PlayCardsRequest, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): PlayCardsRequest = {

    var memberId: Long = 0L
    var cardsOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I64 =>
    
                memberId = readMemberIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                cardsOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'cards' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      memberId,
      cardsOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): PlayCardsRequest =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): PlayCardsRequest = {
    var memberId: Long = 0L
    var cards: String = ""
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I64 =>
                memberId = readMemberIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                cards = readCardsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'cards' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      memberId,
      cards,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    memberId: Long = 0L,
    cards: String = ""
  ): PlayCardsRequest =
    new Immutable(
      memberId,
      cards
    )

  def unapply(_item: PlayCardsRequest): _root_.scala.Option[scala.Product2[Long, String]] = _root_.scala.Some(_item)


  @inline private def readMemberIdValue(_iprot: TProtocol): Long = {
    _iprot.readI64()
  }

  @inline private def writeMemberIdField(memberId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(MemberIdField)
    writeMemberIdValue(memberId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeMemberIdValue(memberId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeI64(memberId_item)
  }

  @inline private def readCardsValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeCardsField(cards_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(CardsField)
    writeCardsValue(cards_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeCardsValue(cards_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(cards_item)
  }


  object Immutable extends ThriftStructCodec3[PlayCardsRequest] {
    override def encode(_item: PlayCardsRequest, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): PlayCardsRequest = PlayCardsRequest.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[PlayCardsRequest] = PlayCardsRequest.metaData
  }

  /**
   * The default read-only implementation of PlayCardsRequest.  You typically should not need to
   * directly reference this class; instead, use the PlayCardsRequest.apply method to construct
   * new instances.
   */
  class Immutable(
      val memberId: Long,
      val cards: String,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PlayCardsRequest {
    def this(
      memberId: Long = 0L,
      cards: String = ""
    ) = this(
      memberId,
      cards,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val memberId: Long,
      cardsOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PlayCardsRequest {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val cards: String =
      if (cardsOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, cardsOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the PlayCardsRequest trait with additional state or
   * behavior and implement the read-only methods from PlayCardsRequest using an underlying
   * instance.
   */
  trait Proxy extends PlayCardsRequest {
    protected def _underlying_PlayCardsRequest: PlayCardsRequest
    override def memberId: Long = _underlying_PlayCardsRequest.memberId
    override def cards: String = _underlying_PlayCardsRequest.cards
    override def _passthroughFields = _underlying_PlayCardsRequest._passthroughFields
  }
}

trait PlayCardsRequest
  extends ThriftStruct
  with scala.Product2[Long, String]
  with java.io.Serializable
{
  import PlayCardsRequest._

  def memberId: Long
  def cards: String

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = memberId
  def _2 = cards


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeMemberIdValue(memberId, _oprot)
                _root_.scala.Some(PlayCardsRequest.MemberIdField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (cards ne null) {
                writeCardsValue(cards, _oprot)
                _root_.scala.Some(PlayCardsRequest.CardsField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): PlayCardsRequest = {
    var memberId: Long = this.memberId
    var cards: String = this.cards
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        memberId = readMemberIdValue(_blob.read)
      case 2 =>
        cards = readCardsValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      memberId,
      cards,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): PlayCardsRequest = {
    var memberId: Long = this.memberId
    var cards: String = this.cards

    _fieldId match {
      case 1 =>
        memberId = 0L
      case 2 =>
        cards = ""
      case _ =>
    }
    new Immutable(
      memberId,
      cards,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetMemberId: PlayCardsRequest = unsetField(1)

  def unsetCards: PlayCardsRequest = unsetField(2)


  override def write(_oprot: TProtocol): Unit = {
    PlayCardsRequest.validate(this)
    _oprot.writeStructBegin(Struct)
    writeMemberIdField(memberId, _oprot)
    if (cards ne null) writeCardsField(cards, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    memberId: Long = this.memberId,
    cards: String = this.cards,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): PlayCardsRequest =
    new Immutable(
      memberId,
      cards,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[PlayCardsRequest]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[PlayCardsRequest]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.memberId
    case 1 => this.cards
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "PlayCardsRequest"
}