/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.game.rpc.domain

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftService, ThriftStruct,
  ThriftStructCodec, ThriftStructCodec3,
  ThriftStructFieldInfo, ThriftResponse, ThriftUtil, ToThriftService}
import com.twitter.finagle.{service => ctfs}
import com.twitter.finagle.thrift.{Protocols, ThriftClientRequest, ThriftServiceIface}
import com.twitter.util.Future
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.transport.TTransport
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryBuffer
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.{
  Builder,
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}
import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
trait GameEndpoint[+MM[_]] extends ThriftService {
  
  def checkGameStatus(traceId: String, request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest): MM[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse]
  
  def joinGame(traceId: String, request: com.jxjxgo.game.rpc.domain.JoinGameRequest): MM[com.jxjxgo.game.rpc.domain.JoinGameResponse]
  
  def playCards(traceId: String, request: com.jxjxgo.game.rpc.domain.PlayCardsRequest): MM[com.jxjxgo.game.rpc.domain.PlayCardsResponse]
  
  def setGameStatus(traceId: String, memberId: Long, gameStatus: String): MM[com.jxjxgo.game.rpc.domain.GameBaseResponse]
}



object GameEndpoint { self =>

  case class ServiceIface(
      checkGameStatus : com.twitter.finagle.Service[self.CheckGameStatus.Args, self.CheckGameStatus.Result],
      joinGame : com.twitter.finagle.Service[self.JoinGame.Args, self.JoinGame.Result],
      playCards : com.twitter.finagle.Service[self.PlayCards.Args, self.PlayCards.Result],
      setGameStatus : com.twitter.finagle.Service[self.SetGameStatus.Args, self.SetGameStatus.Result]
  ) extends BaseServiceIface

  // This is needed to support service inheritance.
  trait BaseServiceIface extends ToThriftService {
    def checkGameStatus : com.twitter.finagle.Service[self.CheckGameStatus.Args, self.CheckGameStatus.Result]
    def joinGame : com.twitter.finagle.Service[self.JoinGame.Args, self.JoinGame.Result]
    def playCards : com.twitter.finagle.Service[self.PlayCards.Args, self.PlayCards.Result]
    def setGameStatus : com.twitter.finagle.Service[self.SetGameStatus.Args, self.SetGameStatus.Result]

    override def toThriftService: ThriftService = new MethodIface(this)
  }

  implicit object ServiceIfaceBuilder
    extends com.twitter.finagle.thrift.ServiceIfaceBuilder[ServiceIface] {
      def newServiceIface(
        binaryService: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
        pf: TProtocolFactory = Protocols.binaryFactory(),
        stats: com.twitter.finagle.stats.StatsReceiver
      ): ServiceIface =
        new ServiceIface(
          checkGameStatus = ThriftServiceIface(self.CheckGameStatus, binaryService, pf, stats),
          joinGame = ThriftServiceIface(self.JoinGame, binaryService, pf, stats),
          playCards = ThriftServiceIface(self.PlayCards, binaryService, pf, stats),
          setGameStatus = ThriftServiceIface(self.SetGameStatus, binaryService, pf, stats)
      )
  }

  class MethodIface(serviceIface: BaseServiceIface)
    extends GameEndpoint[Future] {
    private[this] val __checkGameStatus_service =
      ThriftServiceIface.resultFilter(self.CheckGameStatus) andThen serviceIface.checkGameStatus
    def checkGameStatus(traceId: String, request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest): Future[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse] =
      __checkGameStatus_service(self.CheckGameStatus.Args(traceId, request))
    private[this] val __joinGame_service =
      ThriftServiceIface.resultFilter(self.JoinGame) andThen serviceIface.joinGame
    def joinGame(traceId: String, request: com.jxjxgo.game.rpc.domain.JoinGameRequest): Future[com.jxjxgo.game.rpc.domain.JoinGameResponse] =
      __joinGame_service(self.JoinGame.Args(traceId, request))
    private[this] val __playCards_service =
      ThriftServiceIface.resultFilter(self.PlayCards) andThen serviceIface.playCards
    def playCards(traceId: String, request: com.jxjxgo.game.rpc.domain.PlayCardsRequest): Future[com.jxjxgo.game.rpc.domain.PlayCardsResponse] =
      __playCards_service(self.PlayCards.Args(traceId, request))
    private[this] val __setGameStatus_service =
      ThriftServiceIface.resultFilter(self.SetGameStatus) andThen serviceIface.setGameStatus
    def setGameStatus(traceId: String, memberId: Long, gameStatus: String): Future[com.jxjxgo.game.rpc.domain.GameBaseResponse] =
      __setGameStatus_service(self.SetGameStatus.Args(traceId, memberId, gameStatus))
  }

  implicit object MethodIfaceBuilder
    extends com.twitter.finagle.thrift.MethodIfaceBuilder[ServiceIface, GameEndpoint[Future]] {
    def newMethodIface(serviceIface: ServiceIface): GameEndpoint[Future] =
      new MethodIface(serviceIface)
  }

  object CheckGameStatus extends com.twitter.scrooge.ThriftMethod {
    
    object Args extends ThriftStructCodec3[Args] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("checkGameStatus_args")
      val TraceIdField = new TField("traceId", TType.STRING, 1)
      val TraceIdFieldManifest = implicitly[Manifest[String]]
      val RequestField = new TField("request", TType.STRUCT, 2)
      val RequestFieldManifest = implicitly[Manifest[com.jxjxgo.game.rpc.domain.CheckGameStatusRequest]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          TraceIdField,
          false,
          false,
          TraceIdFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        ),
        new ThriftStructFieldInfo(
          RequestField,
          false,
          false,
          RequestFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Args): Unit = {
      }
    
      def withoutPassthroughFields(original: Args): Args =
        new Args(
          traceId =
            {
              val field = original.traceId
              field
            },
          request =
            {
              val field = original.request
              com.jxjxgo.game.rpc.domain.CheckGameStatusRequest.withoutPassthroughFields(field)
            }
        )
    
      override def encode(_item: Args, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Args = {
        var traceId: String = null
        var request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest = null
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 1 =>
                _field.`type` match {
                  case TType.STRING =>
                    traceId = readTraceIdValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRING
                    throw new TProtocolException(
                      "Received wrong type for field 'traceId' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case 2 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    request = readRequestValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'request' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Args(
          traceId,
          request,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        traceId: String,
        request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest
      ): Args =
        new Args(
          traceId,
          request
        )
    
      def unapply(_item: Args): _root_.scala.Option[scala.Product2[String, com.jxjxgo.game.rpc.domain.CheckGameStatusRequest]] = _root_.scala.Some(_item)
    
    
      @inline private def readTraceIdValue(_iprot: TProtocol): String = {
        _iprot.readString()
      }
    
      @inline private def writeTraceIdField(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(TraceIdField)
        writeTraceIdValue(traceId_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeTraceIdValue(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(traceId_item)
      }
    
      @inline private def readRequestValue(_iprot: TProtocol): com.jxjxgo.game.rpc.domain.CheckGameStatusRequest = {
        com.jxjxgo.game.rpc.domain.CheckGameStatusRequest.decode(_iprot)
      }
    
      @inline private def writeRequestField(request_item: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(RequestField)
        writeRequestValue(request_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeRequestValue(request_item: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest, _oprot: TProtocol): Unit = {
        request_item.write(_oprot)
      }
    
    
    }
    
    class Args(
        val traceId: String,
        val request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest,
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftStruct
      with scala.Product2[String, com.jxjxgo.game.rpc.domain.CheckGameStatusRequest]
      with java.io.Serializable
    {
      import Args._
      def this(
        traceId: String,
        request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest
      ) = this(
        traceId,
        request,
        Map.empty
      )
    
      def _1 = traceId
      def _2 = request
    
    
    
      override def write(_oprot: TProtocol): Unit = {
        Args.validate(this)
        _oprot.writeStructBegin(Struct)
        if (traceId ne null) writeTraceIdField(traceId, _oprot)
        if (request ne null) writeRequestField(request, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        traceId: String = this.traceId,
        request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest = this.request,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Args =
        new Args(
          traceId,
          request,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Args]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Args]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 2
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.traceId
        case 1 => this.request
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Args"
    }

    type SuccessType = com.jxjxgo.game.rpc.domain.CheckGameStatusResponse
    
    object Result extends ThriftStructCodec3[Result] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("checkGameStatus_result")
      val SuccessField = new TField("success", TType.STRUCT, 0)
      val SuccessFieldManifest = implicitly[Manifest[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          SuccessField,
          true,
          false,
          SuccessFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Result): Unit = {
      }
    
      def withoutPassthroughFields(original: Result): Result =
        new Result(
          success =
            {
              val field = original.success
              field.map { field =>
                com.jxjxgo.game.rpc.domain.CheckGameStatusResponse.withoutPassthroughFields(field)
              }
            }
        )
    
      override def encode(_item: Result, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Result = {
        var success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse] = _root_.scala.None
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 0 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    success = _root_.scala.Some(readSuccessValue(_iprot))
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'success' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Result(
          success,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse] = _root_.scala.None
      ): Result =
        new Result(
          success
        )
    
      def unapply(_item: Result): _root_.scala.Option[_root_.scala.Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse]] = _root_.scala.Some(_item.success)
    
    
      @inline private def readSuccessValue(_iprot: TProtocol): com.jxjxgo.game.rpc.domain.CheckGameStatusResponse = {
        com.jxjxgo.game.rpc.domain.CheckGameStatusResponse.decode(_iprot)
      }
    
      @inline private def writeSuccessField(success_item: com.jxjxgo.game.rpc.domain.CheckGameStatusResponse, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(SuccessField)
        writeSuccessValue(success_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeSuccessValue(success_item: com.jxjxgo.game.rpc.domain.CheckGameStatusResponse, _oprot: TProtocol): Unit = {
        success_item.write(_oprot)
      }
    
    
    }
    
    class Result(
        val success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse],
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftResponse[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse] with ThriftStruct
      with scala.Product1[Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse]]
      with java.io.Serializable
    {
      import Result._
      def this(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse] = _root_.scala.None
      ) = this(
        success,
        Map.empty
      )
    
      def _1 = success
    
      def successField: Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse] = success
      def exceptionFields: Iterable[Option[com.twitter.scrooge.ThriftException]] = Seq()
    
    
      override def write(_oprot: TProtocol): Unit = {
        Result.validate(this)
        _oprot.writeStructBegin(Struct)
        if (success.isDefined) writeSuccessField(success.get, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse] = this.success,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Result =
        new Result(
          success,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Result]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Result]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 1
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.success
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Result"
    }

    type FunctionType = Function1[Args,Future[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse]]
    type ServiceType = com.twitter.finagle.Service[Args, Result]

    private[this] val toResult = (res: SuccessType) => Result(Some(res))

    def functionToService(f: FunctionType): ServiceType = {
      com.twitter.finagle.Service.mk { args: Args =>
        f(args).map(toResult)
      }
    }

    def serviceToFunction(svc: ServiceType): FunctionType = { args: Args =>
      ThriftServiceIface.resultFilter(this).andThen(svc).apply(args)
    }

    val name = "checkGameStatus"
    val serviceName = "GameEndpoint"
    val argsCodec = Args
    val responseCodec = Result
    val oneway = false
  }

  // Compatibility aliases.
  val checkGameStatus$args = CheckGameStatus.Args
  type checkGameStatus$args = CheckGameStatus.Args

  val checkGameStatus$result = CheckGameStatus.Result
  type checkGameStatus$result = CheckGameStatus.Result

  object JoinGame extends com.twitter.scrooge.ThriftMethod {
    
    object Args extends ThriftStructCodec3[Args] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("joinGame_args")
      val TraceIdField = new TField("traceId", TType.STRING, 1)
      val TraceIdFieldManifest = implicitly[Manifest[String]]
      val RequestField = new TField("request", TType.STRUCT, 2)
      val RequestFieldManifest = implicitly[Manifest[com.jxjxgo.game.rpc.domain.JoinGameRequest]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          TraceIdField,
          false,
          false,
          TraceIdFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        ),
        new ThriftStructFieldInfo(
          RequestField,
          false,
          false,
          RequestFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Args): Unit = {
      }
    
      def withoutPassthroughFields(original: Args): Args =
        new Args(
          traceId =
            {
              val field = original.traceId
              field
            },
          request =
            {
              val field = original.request
              com.jxjxgo.game.rpc.domain.JoinGameRequest.withoutPassthroughFields(field)
            }
        )
    
      override def encode(_item: Args, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Args = {
        var traceId: String = null
        var request: com.jxjxgo.game.rpc.domain.JoinGameRequest = null
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 1 =>
                _field.`type` match {
                  case TType.STRING =>
                    traceId = readTraceIdValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRING
                    throw new TProtocolException(
                      "Received wrong type for field 'traceId' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case 2 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    request = readRequestValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'request' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Args(
          traceId,
          request,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        traceId: String,
        request: com.jxjxgo.game.rpc.domain.JoinGameRequest
      ): Args =
        new Args(
          traceId,
          request
        )
    
      def unapply(_item: Args): _root_.scala.Option[scala.Product2[String, com.jxjxgo.game.rpc.domain.JoinGameRequest]] = _root_.scala.Some(_item)
    
    
      @inline private def readTraceIdValue(_iprot: TProtocol): String = {
        _iprot.readString()
      }
    
      @inline private def writeTraceIdField(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(TraceIdField)
        writeTraceIdValue(traceId_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeTraceIdValue(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(traceId_item)
      }
    
      @inline private def readRequestValue(_iprot: TProtocol): com.jxjxgo.game.rpc.domain.JoinGameRequest = {
        com.jxjxgo.game.rpc.domain.JoinGameRequest.decode(_iprot)
      }
    
      @inline private def writeRequestField(request_item: com.jxjxgo.game.rpc.domain.JoinGameRequest, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(RequestField)
        writeRequestValue(request_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeRequestValue(request_item: com.jxjxgo.game.rpc.domain.JoinGameRequest, _oprot: TProtocol): Unit = {
        request_item.write(_oprot)
      }
    
    
    }
    
    class Args(
        val traceId: String,
        val request: com.jxjxgo.game.rpc.domain.JoinGameRequest,
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftStruct
      with scala.Product2[String, com.jxjxgo.game.rpc.domain.JoinGameRequest]
      with java.io.Serializable
    {
      import Args._
      def this(
        traceId: String,
        request: com.jxjxgo.game.rpc.domain.JoinGameRequest
      ) = this(
        traceId,
        request,
        Map.empty
      )
    
      def _1 = traceId
      def _2 = request
    
    
    
      override def write(_oprot: TProtocol): Unit = {
        Args.validate(this)
        _oprot.writeStructBegin(Struct)
        if (traceId ne null) writeTraceIdField(traceId, _oprot)
        if (request ne null) writeRequestField(request, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        traceId: String = this.traceId,
        request: com.jxjxgo.game.rpc.domain.JoinGameRequest = this.request,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Args =
        new Args(
          traceId,
          request,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Args]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Args]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 2
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.traceId
        case 1 => this.request
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Args"
    }

    type SuccessType = com.jxjxgo.game.rpc.domain.JoinGameResponse
    
    object Result extends ThriftStructCodec3[Result] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("joinGame_result")
      val SuccessField = new TField("success", TType.STRUCT, 0)
      val SuccessFieldManifest = implicitly[Manifest[com.jxjxgo.game.rpc.domain.JoinGameResponse]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          SuccessField,
          true,
          false,
          SuccessFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Result): Unit = {
      }
    
      def withoutPassthroughFields(original: Result): Result =
        new Result(
          success =
            {
              val field = original.success
              field.map { field =>
                com.jxjxgo.game.rpc.domain.JoinGameResponse.withoutPassthroughFields(field)
              }
            }
        )
    
      override def encode(_item: Result, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Result = {
        var success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.JoinGameResponse] = _root_.scala.None
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 0 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    success = _root_.scala.Some(readSuccessValue(_iprot))
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'success' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Result(
          success,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.JoinGameResponse] = _root_.scala.None
      ): Result =
        new Result(
          success
        )
    
      def unapply(_item: Result): _root_.scala.Option[_root_.scala.Option[com.jxjxgo.game.rpc.domain.JoinGameResponse]] = _root_.scala.Some(_item.success)
    
    
      @inline private def readSuccessValue(_iprot: TProtocol): com.jxjxgo.game.rpc.domain.JoinGameResponse = {
        com.jxjxgo.game.rpc.domain.JoinGameResponse.decode(_iprot)
      }
    
      @inline private def writeSuccessField(success_item: com.jxjxgo.game.rpc.domain.JoinGameResponse, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(SuccessField)
        writeSuccessValue(success_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeSuccessValue(success_item: com.jxjxgo.game.rpc.domain.JoinGameResponse, _oprot: TProtocol): Unit = {
        success_item.write(_oprot)
      }
    
    
    }
    
    class Result(
        val success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.JoinGameResponse],
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftResponse[com.jxjxgo.game.rpc.domain.JoinGameResponse] with ThriftStruct
      with scala.Product1[Option[com.jxjxgo.game.rpc.domain.JoinGameResponse]]
      with java.io.Serializable
    {
      import Result._
      def this(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.JoinGameResponse] = _root_.scala.None
      ) = this(
        success,
        Map.empty
      )
    
      def _1 = success
    
      def successField: Option[com.jxjxgo.game.rpc.domain.JoinGameResponse] = success
      def exceptionFields: Iterable[Option[com.twitter.scrooge.ThriftException]] = Seq()
    
    
      override def write(_oprot: TProtocol): Unit = {
        Result.validate(this)
        _oprot.writeStructBegin(Struct)
        if (success.isDefined) writeSuccessField(success.get, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.JoinGameResponse] = this.success,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Result =
        new Result(
          success,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Result]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Result]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 1
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.success
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Result"
    }

    type FunctionType = Function1[Args,Future[com.jxjxgo.game.rpc.domain.JoinGameResponse]]
    type ServiceType = com.twitter.finagle.Service[Args, Result]

    private[this] val toResult = (res: SuccessType) => Result(Some(res))

    def functionToService(f: FunctionType): ServiceType = {
      com.twitter.finagle.Service.mk { args: Args =>
        f(args).map(toResult)
      }
    }

    def serviceToFunction(svc: ServiceType): FunctionType = { args: Args =>
      ThriftServiceIface.resultFilter(this).andThen(svc).apply(args)
    }

    val name = "joinGame"
    val serviceName = "GameEndpoint"
    val argsCodec = Args
    val responseCodec = Result
    val oneway = false
  }

  // Compatibility aliases.
  val joinGame$args = JoinGame.Args
  type joinGame$args = JoinGame.Args

  val joinGame$result = JoinGame.Result
  type joinGame$result = JoinGame.Result

  object PlayCards extends com.twitter.scrooge.ThriftMethod {
    
    object Args extends ThriftStructCodec3[Args] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("playCards_args")
      val TraceIdField = new TField("traceId", TType.STRING, 1)
      val TraceIdFieldManifest = implicitly[Manifest[String]]
      val RequestField = new TField("request", TType.STRUCT, 2)
      val RequestFieldManifest = implicitly[Manifest[com.jxjxgo.game.rpc.domain.PlayCardsRequest]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          TraceIdField,
          false,
          false,
          TraceIdFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        ),
        new ThriftStructFieldInfo(
          RequestField,
          false,
          false,
          RequestFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Args): Unit = {
      }
    
      def withoutPassthroughFields(original: Args): Args =
        new Args(
          traceId =
            {
              val field = original.traceId
              field
            },
          request =
            {
              val field = original.request
              com.jxjxgo.game.rpc.domain.PlayCardsRequest.withoutPassthroughFields(field)
            }
        )
    
      override def encode(_item: Args, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Args = {
        var traceId: String = null
        var request: com.jxjxgo.game.rpc.domain.PlayCardsRequest = null
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 1 =>
                _field.`type` match {
                  case TType.STRING =>
                    traceId = readTraceIdValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRING
                    throw new TProtocolException(
                      "Received wrong type for field 'traceId' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case 2 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    request = readRequestValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'request' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Args(
          traceId,
          request,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        traceId: String,
        request: com.jxjxgo.game.rpc.domain.PlayCardsRequest
      ): Args =
        new Args(
          traceId,
          request
        )
    
      def unapply(_item: Args): _root_.scala.Option[scala.Product2[String, com.jxjxgo.game.rpc.domain.PlayCardsRequest]] = _root_.scala.Some(_item)
    
    
      @inline private def readTraceIdValue(_iprot: TProtocol): String = {
        _iprot.readString()
      }
    
      @inline private def writeTraceIdField(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(TraceIdField)
        writeTraceIdValue(traceId_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeTraceIdValue(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(traceId_item)
      }
    
      @inline private def readRequestValue(_iprot: TProtocol): com.jxjxgo.game.rpc.domain.PlayCardsRequest = {
        com.jxjxgo.game.rpc.domain.PlayCardsRequest.decode(_iprot)
      }
    
      @inline private def writeRequestField(request_item: com.jxjxgo.game.rpc.domain.PlayCardsRequest, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(RequestField)
        writeRequestValue(request_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeRequestValue(request_item: com.jxjxgo.game.rpc.domain.PlayCardsRequest, _oprot: TProtocol): Unit = {
        request_item.write(_oprot)
      }
    
    
    }
    
    class Args(
        val traceId: String,
        val request: com.jxjxgo.game.rpc.domain.PlayCardsRequest,
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftStruct
      with scala.Product2[String, com.jxjxgo.game.rpc.domain.PlayCardsRequest]
      with java.io.Serializable
    {
      import Args._
      def this(
        traceId: String,
        request: com.jxjxgo.game.rpc.domain.PlayCardsRequest
      ) = this(
        traceId,
        request,
        Map.empty
      )
    
      def _1 = traceId
      def _2 = request
    
    
    
      override def write(_oprot: TProtocol): Unit = {
        Args.validate(this)
        _oprot.writeStructBegin(Struct)
        if (traceId ne null) writeTraceIdField(traceId, _oprot)
        if (request ne null) writeRequestField(request, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        traceId: String = this.traceId,
        request: com.jxjxgo.game.rpc.domain.PlayCardsRequest = this.request,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Args =
        new Args(
          traceId,
          request,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Args]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Args]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 2
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.traceId
        case 1 => this.request
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Args"
    }

    type SuccessType = com.jxjxgo.game.rpc.domain.PlayCardsResponse
    
    object Result extends ThriftStructCodec3[Result] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("playCards_result")
      val SuccessField = new TField("success", TType.STRUCT, 0)
      val SuccessFieldManifest = implicitly[Manifest[com.jxjxgo.game.rpc.domain.PlayCardsResponse]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          SuccessField,
          true,
          false,
          SuccessFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Result): Unit = {
      }
    
      def withoutPassthroughFields(original: Result): Result =
        new Result(
          success =
            {
              val field = original.success
              field.map { field =>
                com.jxjxgo.game.rpc.domain.PlayCardsResponse.withoutPassthroughFields(field)
              }
            }
        )
    
      override def encode(_item: Result, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Result = {
        var success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse] = _root_.scala.None
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 0 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    success = _root_.scala.Some(readSuccessValue(_iprot))
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'success' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Result(
          success,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse] = _root_.scala.None
      ): Result =
        new Result(
          success
        )
    
      def unapply(_item: Result): _root_.scala.Option[_root_.scala.Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse]] = _root_.scala.Some(_item.success)
    
    
      @inline private def readSuccessValue(_iprot: TProtocol): com.jxjxgo.game.rpc.domain.PlayCardsResponse = {
        com.jxjxgo.game.rpc.domain.PlayCardsResponse.decode(_iprot)
      }
    
      @inline private def writeSuccessField(success_item: com.jxjxgo.game.rpc.domain.PlayCardsResponse, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(SuccessField)
        writeSuccessValue(success_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeSuccessValue(success_item: com.jxjxgo.game.rpc.domain.PlayCardsResponse, _oprot: TProtocol): Unit = {
        success_item.write(_oprot)
      }
    
    
    }
    
    class Result(
        val success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse],
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftResponse[com.jxjxgo.game.rpc.domain.PlayCardsResponse] with ThriftStruct
      with scala.Product1[Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse]]
      with java.io.Serializable
    {
      import Result._
      def this(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse] = _root_.scala.None
      ) = this(
        success,
        Map.empty
      )
    
      def _1 = success
    
      def successField: Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse] = success
      def exceptionFields: Iterable[Option[com.twitter.scrooge.ThriftException]] = Seq()
    
    
      override def write(_oprot: TProtocol): Unit = {
        Result.validate(this)
        _oprot.writeStructBegin(Struct)
        if (success.isDefined) writeSuccessField(success.get, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.PlayCardsResponse] = this.success,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Result =
        new Result(
          success,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Result]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Result]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 1
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.success
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Result"
    }

    type FunctionType = Function1[Args,Future[com.jxjxgo.game.rpc.domain.PlayCardsResponse]]
    type ServiceType = com.twitter.finagle.Service[Args, Result]

    private[this] val toResult = (res: SuccessType) => Result(Some(res))

    def functionToService(f: FunctionType): ServiceType = {
      com.twitter.finagle.Service.mk { args: Args =>
        f(args).map(toResult)
      }
    }

    def serviceToFunction(svc: ServiceType): FunctionType = { args: Args =>
      ThriftServiceIface.resultFilter(this).andThen(svc).apply(args)
    }

    val name = "playCards"
    val serviceName = "GameEndpoint"
    val argsCodec = Args
    val responseCodec = Result
    val oneway = false
  }

  // Compatibility aliases.
  val playCards$args = PlayCards.Args
  type playCards$args = PlayCards.Args

  val playCards$result = PlayCards.Result
  type playCards$result = PlayCards.Result

  object SetGameStatus extends com.twitter.scrooge.ThriftMethod {
    
    object Args extends ThriftStructCodec3[Args] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("setGameStatus_args")
      val TraceIdField = new TField("traceId", TType.STRING, 1)
      val TraceIdFieldManifest = implicitly[Manifest[String]]
      val MemberIdField = new TField("memberId", TType.I64, 2)
      val MemberIdFieldManifest = implicitly[Manifest[Long]]
      val GameStatusField = new TField("gameStatus", TType.STRING, 3)
      val GameStatusFieldManifest = implicitly[Manifest[String]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          TraceIdField,
          false,
          false,
          TraceIdFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        ),
        new ThriftStructFieldInfo(
          MemberIdField,
          false,
          false,
          MemberIdFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        ),
        new ThriftStructFieldInfo(
          GameStatusField,
          false,
          false,
          GameStatusFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Args): Unit = {
      }
    
      def withoutPassthroughFields(original: Args): Args =
        new Args(
          traceId =
            {
              val field = original.traceId
              field
            },
          memberId =
            {
              val field = original.memberId
              field
            },
          gameStatus =
            {
              val field = original.gameStatus
              field
            }
        )
    
      override def encode(_item: Args, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Args = {
        var traceId: String = null
        var memberId: Long = 0L
        var gameStatus: String = null
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 1 =>
                _field.`type` match {
                  case TType.STRING =>
                    traceId = readTraceIdValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRING
                    throw new TProtocolException(
                      "Received wrong type for field 'traceId' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case 2 =>
                _field.`type` match {
                  case TType.I64 =>
                    memberId = readMemberIdValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.I64
                    throw new TProtocolException(
                      "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case 3 =>
                _field.`type` match {
                  case TType.STRING =>
                    gameStatus = readGameStatusValue(_iprot)
                  case _actualType =>
                    val _expectedType = TType.STRING
                    throw new TProtocolException(
                      "Received wrong type for field 'gameStatus' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Args(
          traceId,
          memberId,
          gameStatus,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        traceId: String,
        memberId: Long,
        gameStatus: String
      ): Args =
        new Args(
          traceId,
          memberId,
          gameStatus
        )
    
      def unapply(_item: Args): _root_.scala.Option[scala.Product3[String, Long, String]] = _root_.scala.Some(_item)
    
    
      @inline private def readTraceIdValue(_iprot: TProtocol): String = {
        _iprot.readString()
      }
    
      @inline private def writeTraceIdField(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(TraceIdField)
        writeTraceIdValue(traceId_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeTraceIdValue(traceId_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(traceId_item)
      }
    
      @inline private def readMemberIdValue(_iprot: TProtocol): Long = {
        _iprot.readI64()
      }
    
      @inline private def writeMemberIdField(memberId_item: Long, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(MemberIdField)
        writeMemberIdValue(memberId_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeMemberIdValue(memberId_item: Long, _oprot: TProtocol): Unit = {
        _oprot.writeI64(memberId_item)
      }
    
      @inline private def readGameStatusValue(_iprot: TProtocol): String = {
        _iprot.readString()
      }
    
      @inline private def writeGameStatusField(gameStatus_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(GameStatusField)
        writeGameStatusValue(gameStatus_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeGameStatusValue(gameStatus_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(gameStatus_item)
      }
    
    
    }
    
    class Args(
        val traceId: String,
        val memberId: Long,
        val gameStatus: String,
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftStruct
      with scala.Product3[String, Long, String]
      with java.io.Serializable
    {
      import Args._
      def this(
        traceId: String,
        memberId: Long,
        gameStatus: String
      ) = this(
        traceId,
        memberId,
        gameStatus,
        Map.empty
      )
    
      def _1 = traceId
      def _2 = memberId
      def _3 = gameStatus
    
    
    
      override def write(_oprot: TProtocol): Unit = {
        Args.validate(this)
        _oprot.writeStructBegin(Struct)
        if (traceId ne null) writeTraceIdField(traceId, _oprot)
        writeMemberIdField(memberId, _oprot)
        if (gameStatus ne null) writeGameStatusField(gameStatus, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        traceId: String = this.traceId,
        memberId: Long = this.memberId,
        gameStatus: String = this.gameStatus,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Args =
        new Args(
          traceId,
          memberId,
          gameStatus,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Args]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Args]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 3
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.traceId
        case 1 => this.memberId
        case 2 => this.gameStatus
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Args"
    }

    type SuccessType = com.jxjxgo.game.rpc.domain.GameBaseResponse
    
    object Result extends ThriftStructCodec3[Result] {
      private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
      val Struct = new TStruct("setGameStatus_result")
      val SuccessField = new TField("success", TType.STRUCT, 0)
      val SuccessFieldManifest = implicitly[Manifest[com.jxjxgo.game.rpc.domain.GameBaseResponse]]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          SuccessField,
          true,
          false,
          SuccessFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String]
        )
      )
    
      lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Result): Unit = {
      }
    
      def withoutPassthroughFields(original: Result): Result =
        new Result(
          success =
            {
              val field = original.success
              field.map { field =>
                com.jxjxgo.game.rpc.domain.GameBaseResponse.withoutPassthroughFields(field)
              }
            }
        )
    
      override def encode(_item: Result, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
      override def decode(_iprot: TProtocol): Result = {
        var success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.GameBaseResponse] = _root_.scala.None
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 0 =>
                _field.`type` match {
                  case TType.STRUCT =>
                    success = _root_.scala.Some(readSuccessValue(_iprot))
                  case _actualType =>
                    val _expectedType = TType.STRUCT
                    throw new TProtocolException(
                      "Received wrong type for field 'success' (expected=%s, actual=%s).".format(
                        ttypeToString(_expectedType),
                        ttypeToString(_actualType)
                      )
                    )
                }
              case _ =>
                if (_passthroughFields == null)
                  _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
    
        new Result(
          success,
          if (_passthroughFields == null)
            NoPassthroughFields
          else
            _passthroughFields.result()
        )
      }
    
      def apply(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.GameBaseResponse] = _root_.scala.None
      ): Result =
        new Result(
          success
        )
    
      def unapply(_item: Result): _root_.scala.Option[_root_.scala.Option[com.jxjxgo.game.rpc.domain.GameBaseResponse]] = _root_.scala.Some(_item.success)
    
    
      @inline private def readSuccessValue(_iprot: TProtocol): com.jxjxgo.game.rpc.domain.GameBaseResponse = {
        com.jxjxgo.game.rpc.domain.GameBaseResponse.decode(_iprot)
      }
    
      @inline private def writeSuccessField(success_item: com.jxjxgo.game.rpc.domain.GameBaseResponse, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(SuccessField)
        writeSuccessValue(success_item, _oprot)
        _oprot.writeFieldEnd()
      }
    
      @inline private def writeSuccessValue(success_item: com.jxjxgo.game.rpc.domain.GameBaseResponse, _oprot: TProtocol): Unit = {
        success_item.write(_oprot)
      }
    
    
    }
    
    class Result(
        val success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.GameBaseResponse],
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftResponse[com.jxjxgo.game.rpc.domain.GameBaseResponse] with ThriftStruct
      with scala.Product1[Option[com.jxjxgo.game.rpc.domain.GameBaseResponse]]
      with java.io.Serializable
    {
      import Result._
      def this(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.GameBaseResponse] = _root_.scala.None
      ) = this(
        success,
        Map.empty
      )
    
      def _1 = success
    
      def successField: Option[com.jxjxgo.game.rpc.domain.GameBaseResponse] = success
      def exceptionFields: Iterable[Option[com.twitter.scrooge.ThriftException]] = Seq()
    
    
      override def write(_oprot: TProtocol): Unit = {
        Result.validate(this)
        _oprot.writeStructBegin(Struct)
        if (success.isDefined) writeSuccessField(success.get, _oprot)
        if (_passthroughFields.nonEmpty) {
          _passthroughFields.values.foreach { _.write(_oprot) }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
      }
    
      def copy(
        success: _root_.scala.Option[com.jxjxgo.game.rpc.domain.GameBaseResponse] = this.success,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Result =
        new Result(
          success,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Result]
    
      override def equals(other: Any): Boolean =
        canEqual(other) &&
          _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
          _passthroughFields == other.asInstanceOf[Result]._passthroughFields
    
      override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
    
      override def productArity: Int = 1
    
      override def productElement(n: Int): Any = n match {
        case 0 => this.success
        case _ => throw new IndexOutOfBoundsException(n.toString)
      }
    
      override def productPrefix: String = "Result"
    }

    type FunctionType = Function1[Args,Future[com.jxjxgo.game.rpc.domain.GameBaseResponse]]
    type ServiceType = com.twitter.finagle.Service[Args, Result]

    private[this] val toResult = (res: SuccessType) => Result(Some(res))

    def functionToService(f: FunctionType): ServiceType = {
      com.twitter.finagle.Service.mk { args: Args =>
        f(args).map(toResult)
      }
    }

    def serviceToFunction(svc: ServiceType): FunctionType = { args: Args =>
      ThriftServiceIface.resultFilter(this).andThen(svc).apply(args)
    }

    val name = "setGameStatus"
    val serviceName = "GameEndpoint"
    val argsCodec = Args
    val responseCodec = Result
    val oneway = false
  }

  // Compatibility aliases.
  val setGameStatus$args = SetGameStatus.Args
  type setGameStatus$args = SetGameStatus.Args

  val setGameStatus$result = SetGameStatus.Result
  type setGameStatus$result = SetGameStatus.Result


  trait FutureIface extends GameEndpoint[Future] {
    
    def checkGameStatus(traceId: String, request: com.jxjxgo.game.rpc.domain.CheckGameStatusRequest): Future[com.jxjxgo.game.rpc.domain.CheckGameStatusResponse]
    
    def joinGame(traceId: String, request: com.jxjxgo.game.rpc.domain.JoinGameRequest): Future[com.jxjxgo.game.rpc.domain.JoinGameResponse]
    
    def playCards(traceId: String, request: com.jxjxgo.game.rpc.domain.PlayCardsRequest): Future[com.jxjxgo.game.rpc.domain.PlayCardsResponse]
    
    def setGameStatus(traceId: String, memberId: Long, gameStatus: String): Future[com.jxjxgo.game.rpc.domain.GameBaseResponse]
  }

  class FinagledClient(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      protocolFactory: TProtocolFactory = Protocols.binaryFactory(),
      serviceName: String = "GameEndpoint",
      stats: com.twitter.finagle.stats.StatsReceiver = com.twitter.finagle.stats.NullStatsReceiver,
      responseClassifier: ctfs.ResponseClassifier = ctfs.ResponseClassifier.Default)
    extends GameEndpoint$FinagleClient(
      service,
      protocolFactory,
      serviceName,
      stats,
      responseClassifier)
    with FutureIface {

    def this(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      protocolFactory: TProtocolFactory,
      serviceName: String,
      stats: com.twitter.finagle.stats.StatsReceiver
    ) = this(service, protocolFactory, serviceName, stats, ctfs.ResponseClassifier.Default)
  }

  class FinagledService(
      iface: FutureIface,
      protocolFactory: TProtocolFactory)
    extends GameEndpoint$FinagleService(
      iface,
      protocolFactory)
}