/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.game.rpc.domain

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object JoinGameRequest extends ThriftStructCodec3[JoinGameRequest] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("JoinGameRequest")
  val MemberIdField = new TField("memberId", TType.I64, 1)
  val MemberIdFieldManifest = implicitly[Manifest[Long]]
  val FingerPrintField = new TField("fingerPrint", TType.STRING, 2)
  val FingerPrintFieldManifest = implicitly[Manifest[String]]
  val IpField = new TField("ip", TType.I64, 3)
  val IpFieldManifest = implicitly[Manifest[Long]]
  val GameTypeField = new TField("gameType", TType.STRING, 4)
  val GameTypeFieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      MemberIdField,
      false,
      false,
      MemberIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      FingerPrintField,
      false,
      false,
      FingerPrintFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      IpField,
      false,
      false,
      IpFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      GameTypeField,
      false,
      false,
      GameTypeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: JoinGameRequest): Unit = {
  }

  def withoutPassthroughFields(original: JoinGameRequest): JoinGameRequest =
    new Immutable(
      memberId =
        {
          val field = original.memberId
          field
        },
      fingerPrint =
        {
          val field = original.fingerPrint
          field
        },
      ip =
        {
          val field = original.ip
          field
        },
      gameType =
        {
          val field = original.gameType
          field
        }
    )

  override def encode(_item: JoinGameRequest, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): JoinGameRequest = {

    var memberId: Long = 0L
    var fingerPrintOffset: Int = -1
    var ip: Long = 0L
    var gameTypeOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I64 =>
    
                memberId = readMemberIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                fingerPrintOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'fingerPrint' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I64 =>
    
                ip = readIpValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'ip' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.STRING =>
                gameTypeOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'gameType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      memberId,
      fingerPrintOffset,
      ip,
      gameTypeOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): JoinGameRequest =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): JoinGameRequest = {
    var memberId: Long = 0L
    var fingerPrint: String = ""
    var ip: Long = 0L
    var gameType: String = ""
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I64 =>
                memberId = readMemberIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                fingerPrint = readFingerPrintValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'fingerPrint' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I64 =>
                ip = readIpValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'ip' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.STRING =>
                gameType = readGameTypeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'gameType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      memberId,
      fingerPrint,
      ip,
      gameType,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    memberId: Long = 0L,
    fingerPrint: String = "",
    ip: Long = 0L,
    gameType: String = ""
  ): JoinGameRequest =
    new Immutable(
      memberId,
      fingerPrint,
      ip,
      gameType
    )

  def unapply(_item: JoinGameRequest): _root_.scala.Option[scala.Product4[Long, String, Long, String]] = _root_.scala.Some(_item)


  @inline private def readMemberIdValue(_iprot: TProtocol): Long = {
    _iprot.readI64()
  }

  @inline private def writeMemberIdField(memberId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(MemberIdField)
    writeMemberIdValue(memberId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeMemberIdValue(memberId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeI64(memberId_item)
  }

  @inline private def readFingerPrintValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeFingerPrintField(fingerPrint_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(FingerPrintField)
    writeFingerPrintValue(fingerPrint_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeFingerPrintValue(fingerPrint_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(fingerPrint_item)
  }

  @inline private def readIpValue(_iprot: TProtocol): Long = {
    _iprot.readI64()
  }

  @inline private def writeIpField(ip_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(IpField)
    writeIpValue(ip_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeIpValue(ip_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeI64(ip_item)
  }

  @inline private def readGameTypeValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeGameTypeField(gameType_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(GameTypeField)
    writeGameTypeValue(gameType_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeGameTypeValue(gameType_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(gameType_item)
  }


  object Immutable extends ThriftStructCodec3[JoinGameRequest] {
    override def encode(_item: JoinGameRequest, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): JoinGameRequest = JoinGameRequest.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[JoinGameRequest] = JoinGameRequest.metaData
  }

  /**
   * The default read-only implementation of JoinGameRequest.  You typically should not need to
   * directly reference this class; instead, use the JoinGameRequest.apply method to construct
   * new instances.
   */
  class Immutable(
      val memberId: Long,
      val fingerPrint: String,
      val ip: Long,
      val gameType: String,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends JoinGameRequest {
    def this(
      memberId: Long = 0L,
      fingerPrint: String = "",
      ip: Long = 0L,
      gameType: String = ""
    ) = this(
      memberId,
      fingerPrint,
      ip,
      gameType,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val memberId: Long,
      fingerPrintOffset: Int,
      val ip: Long,
      gameTypeOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends JoinGameRequest {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val fingerPrint: String =
      if (fingerPrintOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, fingerPrintOffset)
      }
    lazy val gameType: String =
      if (gameTypeOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, gameTypeOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the JoinGameRequest trait with additional state or
   * behavior and implement the read-only methods from JoinGameRequest using an underlying
   * instance.
   */
  trait Proxy extends JoinGameRequest {
    protected def _underlying_JoinGameRequest: JoinGameRequest
    override def memberId: Long = _underlying_JoinGameRequest.memberId
    override def fingerPrint: String = _underlying_JoinGameRequest.fingerPrint
    override def ip: Long = _underlying_JoinGameRequest.ip
    override def gameType: String = _underlying_JoinGameRequest.gameType
    override def _passthroughFields = _underlying_JoinGameRequest._passthroughFields
  }
}

trait JoinGameRequest
  extends ThriftStruct
  with scala.Product4[Long, String, Long, String]
  with java.io.Serializable
{
  import JoinGameRequest._

  def memberId: Long
  def fingerPrint: String
  def ip: Long
  def gameType: String

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = memberId
  def _2 = fingerPrint
  def _3 = ip
  def _4 = gameType


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeMemberIdValue(memberId, _oprot)
                _root_.scala.Some(JoinGameRequest.MemberIdField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (fingerPrint ne null) {
                writeFingerPrintValue(fingerPrint, _oprot)
                _root_.scala.Some(JoinGameRequest.FingerPrintField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (true) {
                writeIpValue(ip, _oprot)
                _root_.scala.Some(JoinGameRequest.IpField)
              } else {
                _root_.scala.None
              }
            case 4 =>
              if (gameType ne null) {
                writeGameTypeValue(gameType, _oprot)
                _root_.scala.Some(JoinGameRequest.GameTypeField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): JoinGameRequest = {
    var memberId: Long = this.memberId
    var fingerPrint: String = this.fingerPrint
    var ip: Long = this.ip
    var gameType: String = this.gameType
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        memberId = readMemberIdValue(_blob.read)
      case 2 =>
        fingerPrint = readFingerPrintValue(_blob.read)
      case 3 =>
        ip = readIpValue(_blob.read)
      case 4 =>
        gameType = readGameTypeValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      memberId,
      fingerPrint,
      ip,
      gameType,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): JoinGameRequest = {
    var memberId: Long = this.memberId
    var fingerPrint: String = this.fingerPrint
    var ip: Long = this.ip
    var gameType: String = this.gameType

    _fieldId match {
      case 1 =>
        memberId = 0L
      case 2 =>
        fingerPrint = ""
      case 3 =>
        ip = 0L
      case 4 =>
        gameType = ""
      case _ =>
    }
    new Immutable(
      memberId,
      fingerPrint,
      ip,
      gameType,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetMemberId: JoinGameRequest = unsetField(1)

  def unsetFingerPrint: JoinGameRequest = unsetField(2)

  def unsetIp: JoinGameRequest = unsetField(3)

  def unsetGameType: JoinGameRequest = unsetField(4)


  override def write(_oprot: TProtocol): Unit = {
    JoinGameRequest.validate(this)
    _oprot.writeStructBegin(Struct)
    writeMemberIdField(memberId, _oprot)
    if (fingerPrint ne null) writeFingerPrintField(fingerPrint, _oprot)
    writeIpField(ip, _oprot)
    if (gameType ne null) writeGameTypeField(gameType, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    memberId: Long = this.memberId,
    fingerPrint: String = this.fingerPrint,
    ip: Long = this.ip,
    gameType: String = this.gameType,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): JoinGameRequest =
    new Immutable(
      memberId,
      fingerPrint,
      ip,
      gameType,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[JoinGameRequest]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[JoinGameRequest]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 4

  override def productElement(n: Int): Any = n match {
    case 0 => this.memberId
    case 1 => this.fingerPrint
    case 2 => this.ip
    case 3 => this.gameType
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "JoinGameRequest"
}