// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/gamecoordinatecenter.proto

package com.lawsofnature.gamecenter.common.domain;

public final class GameCenterRequest {
  private GameCenterRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JoinRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JoinRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string traceId = 1;</code>
     */
    String getTraceId();
    /**
     * <code>optional string traceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTraceIdBytes();

    /**
     * <code>optional int64 memberId = 2;</code>
     */
    long getMemberId();

    /**
     * <code>optional int32 gameType = 3;</code>
     */
    int getGameType();
  }
  /**
   * Protobuf type {@code JoinRequest}
   */
  public  static final class JoinRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JoinRequest)
      JoinRequestOrBuilder {
    // Use JoinRequest.newBuilder() to construct.
    private JoinRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JoinRequest() {
      traceId_ = "";
      memberId_ = 0L;
      gameType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private JoinRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              traceId_ = s;
              break;
            }
            case 16: {

              memberId_ = input.readInt64();
              break;
            }
            case 24: {

              gameType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lawsofnature.gamecenter.common.domain.GameCenterRequest.internal_static_JoinRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lawsofnature.gamecenter.common.domain.GameCenterRequest.internal_static_JoinRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest.class, com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest.Builder.class);
    }

    public static final int TRACEID_FIELD_NUMBER = 1;
    private volatile Object traceId_;
    /**
     * <code>optional string traceId = 1;</code>
     */
    public String getTraceId() {
      Object ref = traceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string traceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>optional int64 memberId = 2;</code>
     */
    public long getMemberId() {
      return memberId_;
    }

    public static final int GAMETYPE_FIELD_NUMBER = 3;
    private int gameType_;
    /**
     * <code>optional int32 gameType = 3;</code>
     */
    public int getGameType() {
      return gameType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTraceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceId_);
      }
      if (memberId_ != 0L) {
        output.writeInt64(2, memberId_);
      }
      if (gameType_ != 0) {
        output.writeInt32(3, gameType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTraceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceId_);
      }
      if (memberId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, memberId_);
      }
      if (gameType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gameType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest)) {
        return super.equals(obj);
      }
      com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest other = (com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest) obj;

      boolean result = true;
      result = result && getTraceId()
          .equals(other.getTraceId());
      result = result && (getMemberId()
          == other.getMemberId());
      result = result && (getGameType()
          == other.getGameType());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
      hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemberId());
      hash = (37 * hash) + GAMETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getGameType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JoinRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JoinRequest)
        com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lawsofnature.gamecenter.common.domain.GameCenterRequest.internal_static_JoinRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lawsofnature.gamecenter.common.domain.GameCenterRequest.internal_static_JoinRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest.class, com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest.Builder.class);
      }

      // Construct using com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        traceId_ = "";

        memberId_ = 0L;

        gameType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lawsofnature.gamecenter.common.domain.GameCenterRequest.internal_static_JoinRequest_descriptor;
      }

      public com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest getDefaultInstanceForType() {
        return com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest.getDefaultInstance();
      }

      public com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest build() {
        com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest buildPartial() {
        com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest result = new com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest(this);
        result.traceId_ = traceId_;
        result.memberId_ = memberId_;
        result.gameType_ = gameType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest) {
          return mergeFrom((com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest other) {
        if (other == com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest.getDefaultInstance()) return this;
        if (!other.getTraceId().isEmpty()) {
          traceId_ = other.traceId_;
          onChanged();
        }
        if (other.getMemberId() != 0L) {
          setMemberId(other.getMemberId());
        }
        if (other.getGameType() != 0) {
          setGameType(other.getGameType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object traceId_ = "";
      /**
       * <code>optional string traceId = 1;</code>
       */
      public String getTraceId() {
        Object ref = traceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          traceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string traceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTraceIdBytes() {
        Object ref = traceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          traceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string traceId = 1;</code>
       */
      public Builder setTraceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceId = 1;</code>
       */
      public Builder clearTraceId() {
        
        traceId_ = getDefaultInstance().getTraceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceId = 1;</code>
       */
      public Builder setTraceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traceId_ = value;
        onChanged();
        return this;
      }

      private long memberId_ ;
      /**
       * <code>optional int64 memberId = 2;</code>
       */
      public long getMemberId() {
        return memberId_;
      }
      /**
       * <code>optional int64 memberId = 2;</code>
       */
      public Builder setMemberId(long value) {
        
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 memberId = 2;</code>
       */
      public Builder clearMemberId() {
        
        memberId_ = 0L;
        onChanged();
        return this;
      }

      private int gameType_ ;
      /**
       * <code>optional int32 gameType = 3;</code>
       */
      public int getGameType() {
        return gameType_;
      }
      /**
       * <code>optional int32 gameType = 3;</code>
       */
      public Builder setGameType(int value) {
        
        gameType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gameType = 3;</code>
       */
      public Builder clearGameType() {
        
        gameType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:JoinRequest)
    }

    // @@protoc_insertion_point(class_scope:JoinRequest)
    private static final com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest();
    }

    public static com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JoinRequest>
        PARSER = new com.google.protobuf.AbstractParser<JoinRequest>() {
      public JoinRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new JoinRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JoinRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<JoinRequest> getParserForType() {
      return PARSER;
    }

    public com.lawsofnature.gamecenter.common.domain.GameCenterRequest.JoinRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036src/gamecoordinatecenter.proto\"B\n\013Join" +
      "Request\022\017\n\007traceId\030\001 \001(\t\022\020\n\010memberId\030\002 \001" +
      "(\003\022\020\n\010gameType\030\003 \001(\005B7\n\"com.lawsofnature" +
      ".gamecenter.domainB\021GameCenterRequestb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JoinRequest_descriptor,
        new String[] { "TraceId", "MemberId", "GameType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
