// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: socket.proto

package com.lawsofnature.gamecenter.common.domain;

public final class SocketRequest {
    private SocketRequest() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface BaseRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:BaseRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string ti = 1;</code>
         */
        String getTi();

        /**
         * <code>optional string ti = 1;</code>
         */
        com.google.protobuf.ByteString
        getTiBytes();

        /**
         * <code>optional string tk = 2;</code>
         */
        String getTk();

        /**
         * <code>optional string tk = 2;</code>
         */
        com.google.protobuf.ByteString
        getTkBytes();
    }

    /**
     * Protobuf type {@code BaseRequest}
     */
    public static final class BaseRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:BaseRequest)
            BaseRequestOrBuilder {
        // Use BaseRequest.newBuilder() to construct.
        private BaseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BaseRequest() {
            ti_ = "";
            tk_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private BaseRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            ti_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            tk_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SocketRequest.internal_static_BaseRequest_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SocketRequest.internal_static_BaseRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            BaseRequest.class, Builder.class);
        }

        public static final int TI_FIELD_NUMBER = 1;
        private volatile Object ti_;

        /**
         * <code>optional string ti = 1;</code>
         */
        public String getTi() {
            Object ref = ti_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                ti_ = s;
                return s;
            }
        }

        /**
         * <code>optional string ti = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTiBytes() {
            Object ref = ti_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                ti_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TK_FIELD_NUMBER = 2;
        private volatile Object tk_;

        /**
         * <code>optional string tk = 2;</code>
         */
        public String getTk() {
            Object ref = tk_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                tk_ = s;
                return s;
            }
        }

        /**
         * <code>optional string tk = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTkBytes() {
            Object ref = tk_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                tk_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTiBytes().isEmpty()) {
                writeString(output, 1, ti_);
            }
            if (!getTkBytes().isEmpty()) {
                writeString(output, 2, tk_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getTiBytes().isEmpty()) {
                size += computeStringSize(1, ti_);
            }
            if (!getTkBytes().isEmpty()) {
                size += computeStringSize(2, tk_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof BaseRequest)) {
                return super.equals(obj);
            }
            BaseRequest other = (BaseRequest) obj;

            boolean result = true;
            result = result && getTi()
                    .equals(other.getTi());
            result = result && getTk()
                    .equals(other.getTk());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + TI_FIELD_NUMBER;
            hash = (53 * hash) + getTi().hashCode();
            hash = (37 * hash) + TK_FIELD_NUMBER;
            hash = (53 * hash) + getTk().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static BaseRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BaseRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BaseRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BaseRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BaseRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input);
        }

        public static BaseRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static BaseRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedWithIOException(PARSER, input);
        }

        public static BaseRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static BaseRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input);
        }

        public static BaseRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(BaseRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code BaseRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:BaseRequest)
                BaseRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SocketRequest.internal_static_BaseRequest_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SocketRequest.internal_static_BaseRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                BaseRequest.class, Builder.class);
            }

            // Construct using SocketRequest.BaseRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                ti_ = "";

                tk_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SocketRequest.internal_static_BaseRequest_descriptor;
            }

            public BaseRequest getDefaultInstanceForType() {
                return BaseRequest.getDefaultInstance();
            }

            public BaseRequest build() {
                BaseRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public BaseRequest buildPartial() {
                BaseRequest result = new BaseRequest(this);
                result.ti_ = ti_;
                result.tk_ = tk_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof BaseRequest) {
                    return mergeFrom((BaseRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(BaseRequest other) {
                if (other == BaseRequest.getDefaultInstance()) return this;
                if (!other.getTi().isEmpty()) {
                    ti_ = other.ti_;
                    onChanged();
                }
                if (!other.getTk().isEmpty()) {
                    tk_ = other.tk_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                BaseRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (BaseRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object ti_ = "";

            /**
             * <code>optional string ti = 1;</code>
             */
            public String getTi() {
                Object ref = ti_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    ti_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTiBytes() {
                Object ref = ti_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    ti_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public Builder setTi(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ti_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public Builder clearTi() {

                ti_ = getDefaultInstance().getTi();
                onChanged();
                return this;
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public Builder setTiBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ti_ = value;
                onChanged();
                return this;
            }

            private Object tk_ = "";

            /**
             * <code>optional string tk = 2;</code>
             */
            public String getTk() {
                Object ref = tk_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    tk_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTkBytes() {
                Object ref = tk_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    tk_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public Builder setTk(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                tk_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public Builder clearTk() {

                tk_ = getDefaultInstance().getTk();
                onChanged();
                return this;
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public Builder setTkBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                tk_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:BaseRequest)
        }

        // @@protoc_insertion_point(class_scope:BaseRequest)
        private static final BaseRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new BaseRequest();
        }

        public static BaseRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BaseRequest>
                PARSER = new com.google.protobuf.AbstractParser<BaseRequest>() {
            public BaseRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BaseRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<BaseRequest> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<BaseRequest> getParserForType() {
            return PARSER;
        }

        public BaseRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface PlayCardsRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PlayCardsRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string ti = 1;</code>
         */
        String getTi();

        /**
         * <code>optional string ti = 1;</code>
         */
        com.google.protobuf.ByteString
        getTiBytes();

        /**
         * <code>optional string tk = 2;</code>
         */
        String getTk();

        /**
         * <code>optional string tk = 2;</code>
         */
        com.google.protobuf.ByteString
        getTkBytes();

        /**
         * <code>optional string cards = 3;</code>
         */
        String getCards();

        /**
         * <code>optional string cards = 3;</code>
         */
        com.google.protobuf.ByteString
        getCardsBytes();
    }

    /**
     * Protobuf type {@code PlayCardsRequest}
     */
    public static final class PlayCardsRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PlayCardsRequest)
            PlayCardsRequestOrBuilder {
        // Use PlayCardsRequest.newBuilder() to construct.
        private PlayCardsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PlayCardsRequest() {
            ti_ = "";
            tk_ = "";
            cards_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private PlayCardsRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            ti_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            tk_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            cards_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SocketRequest.internal_static_PlayCardsRequest_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SocketRequest.internal_static_PlayCardsRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PlayCardsRequest.class, Builder.class);
        }

        public static final int TI_FIELD_NUMBER = 1;
        private volatile Object ti_;

        /**
         * <code>optional string ti = 1;</code>
         */
        public String getTi() {
            Object ref = ti_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                ti_ = s;
                return s;
            }
        }

        /**
         * <code>optional string ti = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTiBytes() {
            Object ref = ti_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                ti_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TK_FIELD_NUMBER = 2;
        private volatile Object tk_;

        /**
         * <code>optional string tk = 2;</code>
         */
        public String getTk() {
            Object ref = tk_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                tk_ = s;
                return s;
            }
        }

        /**
         * <code>optional string tk = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTkBytes() {
            Object ref = tk_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                tk_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CARDS_FIELD_NUMBER = 3;
        private volatile Object cards_;

        /**
         * <code>optional string cards = 3;</code>
         */
        public String getCards() {
            Object ref = cards_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                cards_ = s;
                return s;
            }
        }

        /**
         * <code>optional string cards = 3;</code>
         */
        public com.google.protobuf.ByteString
        getCardsBytes() {
            Object ref = cards_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                cards_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTiBytes().isEmpty()) {
                writeString(output, 1, ti_);
            }
            if (!getTkBytes().isEmpty()) {
                writeString(output, 2, tk_);
            }
            if (!getCardsBytes().isEmpty()) {
                writeString(output, 3, cards_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getTiBytes().isEmpty()) {
                size += computeStringSize(1, ti_);
            }
            if (!getTkBytes().isEmpty()) {
                size += computeStringSize(2, tk_);
            }
            if (!getCardsBytes().isEmpty()) {
                size += computeStringSize(3, cards_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof PlayCardsRequest)) {
                return super.equals(obj);
            }
            PlayCardsRequest other = (PlayCardsRequest) obj;

            boolean result = true;
            result = result && getTi()
                    .equals(other.getTi());
            result = result && getTk()
                    .equals(other.getTk());
            result = result && getCards()
                    .equals(other.getCards());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + TI_FIELD_NUMBER;
            hash = (53 * hash) + getTi().hashCode();
            hash = (37 * hash) + TK_FIELD_NUMBER;
            hash = (53 * hash) + getTk().hashCode();
            hash = (37 * hash) + CARDS_FIELD_NUMBER;
            hash = (53 * hash) + getCards().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static PlayCardsRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PlayCardsRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PlayCardsRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PlayCardsRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PlayCardsRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input);
        }

        public static PlayCardsRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static PlayCardsRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedWithIOException(PARSER, input);
        }

        public static PlayCardsRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static PlayCardsRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input);
        }

        public static PlayCardsRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(PlayCardsRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code PlayCardsRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PlayCardsRequest)
                PlayCardsRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SocketRequest.internal_static_PlayCardsRequest_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SocketRequest.internal_static_PlayCardsRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                PlayCardsRequest.class, Builder.class);
            }

            // Construct using SocketRequest.PlayCardsRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                ti_ = "";

                tk_ = "";

                cards_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SocketRequest.internal_static_PlayCardsRequest_descriptor;
            }

            public PlayCardsRequest getDefaultInstanceForType() {
                return PlayCardsRequest.getDefaultInstance();
            }

            public PlayCardsRequest build() {
                PlayCardsRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public PlayCardsRequest buildPartial() {
                PlayCardsRequest result = new PlayCardsRequest(this);
                result.ti_ = ti_;
                result.tk_ = tk_;
                result.cards_ = cards_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PlayCardsRequest) {
                    return mergeFrom((PlayCardsRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PlayCardsRequest other) {
                if (other == PlayCardsRequest.getDefaultInstance()) return this;
                if (!other.getTi().isEmpty()) {
                    ti_ = other.ti_;
                    onChanged();
                }
                if (!other.getTk().isEmpty()) {
                    tk_ = other.tk_;
                    onChanged();
                }
                if (!other.getCards().isEmpty()) {
                    cards_ = other.cards_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                PlayCardsRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (PlayCardsRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object ti_ = "";

            /**
             * <code>optional string ti = 1;</code>
             */
            public String getTi() {
                Object ref = ti_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    ti_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTiBytes() {
                Object ref = ti_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    ti_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public Builder setTi(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ti_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public Builder clearTi() {

                ti_ = getDefaultInstance().getTi();
                onChanged();
                return this;
            }

            /**
             * <code>optional string ti = 1;</code>
             */
            public Builder setTiBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ti_ = value;
                onChanged();
                return this;
            }

            private Object tk_ = "";

            /**
             * <code>optional string tk = 2;</code>
             */
            public String getTk() {
                Object ref = tk_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    tk_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTkBytes() {
                Object ref = tk_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    tk_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public Builder setTk(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                tk_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public Builder clearTk() {

                tk_ = getDefaultInstance().getTk();
                onChanged();
                return this;
            }

            /**
             * <code>optional string tk = 2;</code>
             */
            public Builder setTkBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                tk_ = value;
                onChanged();
                return this;
            }

            private Object cards_ = "";

            /**
             * <code>optional string cards = 3;</code>
             */
            public String getCards() {
                Object ref = cards_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    cards_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string cards = 3;</code>
             */
            public com.google.protobuf.ByteString
            getCardsBytes() {
                Object ref = cards_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    cards_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string cards = 3;</code>
             */
            public Builder setCards(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                cards_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string cards = 3;</code>
             */
            public Builder clearCards() {

                cards_ = getDefaultInstance().getCards();
                onChanged();
                return this;
            }

            /**
             * <code>optional string cards = 3;</code>
             */
            public Builder setCardsBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                cards_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:PlayCardsRequest)
        }

        // @@protoc_insertion_point(class_scope:PlayCardsRequest)
        private static final PlayCardsRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new PlayCardsRequest();
        }

        public static PlayCardsRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PlayCardsRequest>
                PARSER = new com.google.protobuf.AbstractParser<PlayCardsRequest>() {
            public PlayCardsRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PlayCardsRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<PlayCardsRequest> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<PlayCardsRequest> getParserForType() {
            return PARSER;
        }

        public PlayCardsRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_BaseRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_BaseRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PlayCardsRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PlayCardsRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\014socket.proto\"%\n\013BaseRequest\022\n\n\002ti\030\001 \001(" +
                        "\t\022\n\n\002tk\030\002 \001(\t\"9\n\020PlayCardsRequest\022\n\n\002ti\030" +
                        "\001 \001(\t\022\n\n\002tk\030\002 \001(\t\022\r\n\005cards\030\003 \001(\tB:\n)com." +
                        "lawsofnature.gamecenter.socket.domainB\rS" +
                        "ocketRequestb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_BaseRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_BaseRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_BaseRequest_descriptor,
                new String[]{"Ti", "Tk",});
        internal_static_PlayCardsRequest_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_PlayCardsRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PlayCardsRequest_descriptor,
                new String[]{"Ti", "Tk", "Cards",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
